version: '3'

services:
  prometheus:
    image: napnap75/rpi-prometheus:prometheus-2.3.2
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prom-data:/prometheus
  node-exporter:
    image: napnap75/rpi-prometheus:node_exporter-0.16.0
  grafana:
    image: fg2it/grafana-armhf:v4.1.2
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - "3000:3000"

volumes:
  prom-data:
  grafana-data:
