version: '3'

services:
  prometheus:
    image: napnap75/rpi-prometheus:prometheus-2.3.2
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prom-data:/prometheus
  node-exporter:
    image: napnap75/rpi-prometheus:node_exporter-0.16.0
    expose:
    - "9100"
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    command:
    - '--path.procfs=/host/proc' 
    - '--path.sysfs=/host/sys'
    - --collector.filesystem.ignored-mount-points
    - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  grafana:
    image: fg2it/grafana-armhf:v4.1.2
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - "3000:3000"
  fritz-box-exporter:
    image: johanneswuerbach/fritzbox_exporter:1
    expose:
    - "9133"
  homematic-exporter:
    image: johanneswuerbach/homematic_exporter:1
    volumes:
    - /dumb-home/config:/usr/src/app/config:ro
    expose:
    - "8000"

volumes:
  prom-data:
  grafana-data:
