{
 "title": "Internet",
 "tags": [ "home" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "gateway_wan_bytes_received" }
   ]
  },
  {
   "title": "Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "gateway_wan_bytes_sent" }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(gateway_wan_bytes_received[5m])"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(gateway_wan_bytes_sent[5m])"
    }
   ]
  }
 ]
}