{
 "title": "Systemd Service Dashboard",
 "description": "Show stats from node_exporter systemd collector.",
 "tags": [ "system" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_systemd_unit_state, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Global Systemd State Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unit State Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Activating",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$Node$\", state=\"activating\"})"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$Node$\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$Node$\", state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^$Node$\", state=\"inactive\"})"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Failed Services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{instance=~\"^.*$\",state=\"failed\"}) by (name, state) > 0"
    }
   ]
  }
 ]
}